swagger: '2.0'
info:
  title: Odin-ah-backend
  description: " A Social platform for the creative at heart."
  version: v1
host: 127.0.0.1:3000
produces:
- application/json
schemes:
- http
- https
paths:
  "/api/vi/auth":
    post:
      summary: Add new user
      consumes:
      - application/json
      produces:
      - application/json
      parameters:

      - in: body
        name: user information
        description: user username
        schema:
          $ref: '#/definitions/UserRequest'
     
      responses:
        "201":
          description: Expected response to a valid request
          schema:
            $ref: '#/definitions/UserResult'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'

definitions:
  UserRequest:
    required:
      - email
      - username
      - password
    properties:
      username:
        type: string
        example: hammed
      email:
        type: string
        example: hnobi08@yahoo.com
      password:
        type: string
        example: password
  
  UserResult:
  
    properties:
      status:
        type: string
        example: success
      message:
        type: string
        example: Please check your Email for account confirmation


        
  Error:

    properties:
      status:
        type: string
        example: failed
      message:
        type: string
        example: user with email hnobi08@gmail.com already have Authors haven account
  
